In this document, we have code to

* Translate code in the form of vcf written by the 1000 Genome people to the raw sequences
* Compare these sequences with reference sequences to create matrices of allele frequency 
* Run PCA analysis on these matrices


In [1]:
### Manual PCA Analysis
### BIOS 26211 Final Project
### Bruno Petrucci and Christian Porras

import numpy as np
import matplotlib.pyplot as plt
import allel
from sklearn.decomposition import PCA

C:\Users\Petrucci\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Following is the code originally created to simulate some random sequences to test the rest of the code

In [2]:
### First create some Reference Sequence just to test the code
Nucleotides = ['A', 'T', 'C', 'G']
ReferenceSequence1 = np.array([np.random.choice(Nucleotides, 10, p=[0.25, 0.25, 0.25, 0.25])])
ReferenceSequence2 = np.array([np.random.choice(Nucleotides, 10, p=[0.25, 0.25, 0.25, 0.25])])
ReferenceSequence = np.append(ReferenceSequence1, ReferenceSequence2, axis=0)
# Of course it's unrealistic for both of them to be random but it's just for testing - this will be the reference

### Create some random sequence to compare
AnalysisSequence1 = np.array([np.random.choice(Nucleotides, 10, p=[0.25, 0.25, 0.25, 0.25])])
AnalysisSequence2 = np.array([np.random.choice(Nucleotides, 10, p=[0.25, 0.25, 0.25, 0.25])])
AnalysisSequence = np.append(AnalysisSequence1, AnalysisSequence2, axis=0)

Here is the function that transforms sequences into matrices with 0, 1 and 2.

In [3]:
### Define the function that transforms the sequence into a PCA-ble matrix
def TransformSequence(Sequence, Reference):
    Transform = np.zeros(Sequence.shape[1])
    for i in range(Sequence.shape[1]):
        if (Sequence[0][i] == Reference[0][i] and Sequence[1][i] == Reference[1][i]) or (Sequence[0][i] == Reference[1][i] and Sequence[1][i] == Reference[0][i]):
            Transform[i] = 0
        elif Sequence[0][i] == Reference[0][i] or Sequence[1][i] == Reference[1][i] or Sequence[0][i] == Reference[1][i] or Sequence[1][i] == Reference[0][i]:
            Transform[i] = 1
        else:
            Transform[i] = 2
        
    return Transform

In [4]:
### Test for the sequences generated above
print(ReferenceSequence)
print(AnalysisSequence)
TransformedSequence = TransformSequence(AnalysisSequence, ReferenceSequence)
print(TransformedSequence)

[['A' 'T' 'A' 'G' 'T' 'T' 'G' 'T' 'C' 'T']
 ['A' 'C' 'A' 'C' 'G' 'A' 'G' 'G' 'C' 'C']]
[['T' 'G' 'C' 'A' 'A' 'A' 'G' 'T' 'T' 'T']
 ['G' 'G' 'G' 'A' 'A' 'G' 'C' 'T' 'G' 'A']]
[2. 2. 2. 2. 2. 1. 1. 1. 2. 1.]


In [5]:
### Generate a bunch of sequences to test the PCA analysis
SequencesGenerated = 10
Sequences = np.array([AnalysisSequence for i in range(SequencesGenerated)])

for i in range(1,SequencesGenerated):
    NewSequence = np.array([np.random.choice(Nucleotides, 10, p=[0.25, 0.25, 0.25, 0.25])])
    Sequences[:][:][i] = NewSequence

TransformedSequences = np.zeros((SequencesGenerated, Sequences.shape[2]))

for i in range(SequencesGenerated):
    TransformedSequences[i,:] = TransformSequence(Sequences[i,:,:], ReferenceSequence)

print(TransformedSequences)

[[2. 2. 2. 2. 2. 1. 1. 1. 2. 1.]
 [2. 1. 2. 2. 1. 2. 2. 1. 0. 2.]
 [0. 2. 2. 1. 2. 2. 2. 2. 0. 2.]
 [2. 2. 2. 1. 2. 1. 0. 2. 0. 2.]
 [2. 2. 2. 2. 1. 2. 0. 2. 2. 2.]
 [2. 2. 2. 2. 1. 2. 0. 2. 2. 2.]
 [0. 1. 2. 1. 2. 2. 2. 1. 2. 1.]
 [2. 2. 0. 2. 1. 2. 2. 2. 2. 1.]
 [2. 1. 2. 2. 1. 2. 2. 2. 2. 1.]
 [2. 1. 0. 1. 1. 2. 2. 2. 0. 2.]]


Now we have the actual 1000 genome data, where we will translate and run PCA on

In [7]:
### Get the actual 1000 Genome 21st Chromosome data
callset = allel.read_vcf('ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz')

In the callset we only have the genotype matrix, so we write code to transform it back into sequences

In [7]:
### Call the genotype matrix
GT = callset['calldata/GT']
GT1 = GT
print(GT.shape)

(1105538, 2504, 2)


In [8]:
Var = np.array(callset['variants/ALT'])
print(Var.shape)

(1105538, 3)


In [9]:
Ref = np.array(callset['variants/REF'])
print(Ref.shape)

(1105538,)


In [10]:
### Define a function to write a sequence from the allel data
def WriteSequence(Reference, Variations, GenMat):
    Sequence1  = np.array([np.repeat('A', len(Reference))])
    Sequence2  = np.array([np.repeat('A', len(Reference))])
    Sequence = np.append(Sequence1, Sequence2, axis = 0)
    
    for i in range(Sequence1.shape[0]):
        Options = np.array([Ref[i], Var[i, 0], Var[i, 1], Var[i, 2]])
        Sequence[:, i] = np.array([Options[GenMat[i, 0]], Options[GenMat[i, 1]]])
    return Sequence.T

In [11]:
### Write the sequences for the 1000 genome data
### Memory error if you try the full length
RawSequence1 = np.array([np.repeat('A', Ref.shape[0])])
RawSequence2 = np.array([np.repeat('A', Ref.shape[0])])
RawSequence = np.array([RawSequence1, RawSequence2]).T
RawSequenceTest = np.array([RawSequence1, RawSequence2]).T
for i in range(GT.shape[1]-1):
    RawSequence = np.append(RawSequence, RawSequenceTest, axis = 1)
print(RawSequence.shape)

for i in range(GT.shape[1]):
    Sequence = WriteSequence(Ref, Var, GT[:, i, :])
    RawSequence[:, i, :] = Sequence

print(RawSequence.shape)

KeyboardInterrupt: 

In [14]:
### Here we transform the GT arrays into 0, 1 and 2 in light of the Novembre paper
GT1[GT1 == 2] = 1
GT1[GT1 == 3] = 1
ConvertedGT = np.sum(GT1, axis=2)
print(ConvertedGT.shape)

MemoryError: 

Finally, we run the PCA

In [13]:
### Define PCA function (using code from my Lab 1)

### The manual PCA returns a Memory Error, have to figure out
### So does the sklearn PCA sigh
def ManualPCA(M, d, k):
    if (d == 0):
        Row = True
    elif (d == 1):
        Row = False
    else:
        return 0
    CovM = np.cov(M, rowvar = Row)
    eVals, eVecs = np.linalg.eig(CovM)
    CoefDet = eVals/sum(eVals)
    
    return eVecs[:,0:k], CoefDet[0:k]

pca = PCA(n_components=2)
PCs = pca.fit_transform(ConvertedGT)

NameError: name 'ConvertedGT' is not defined

In [ ]:
### Memory error as above
ConvertedGTProj1 = ConvertedGT.T@PCs[:, 0]
ConvertedGTProj2 = ConvertedGT.T@PCs[:, 1]

plt.scatter(ConvertedGTProj1, ConvertedGTProj2)

Now we do a rudimentary linkage filtering before the PCA - we divide the GT rows into $1000$ pieces, and sample randomly from the inner $500$ of each piece

In [ ]:
SegmentLength = 1000
NumSegments = int(ConvertedGT.shape[0]/SegmentLength)
Remainder = ConvertedGT.shape[0] % NumSegments
Indices = np.array([NumSegments*i for i in range(int(ConvertedGT.shape[0]/NumSegments)+1)])

Samples = np.zeros((len(Indices), GT.shape[1], GT.shape[2]))
ConvertedSamples = np.zeros((len(Indices), ConvertedGT.shape[1]))
RefSegment = np.repeat('A', len(Indices))
VarSegment =np.array([np.repeat('A', len(Indices)), np.repeat('A', len(Indices)), np.repeat('A', len(Indices))]).T
ConvertedGTRows = range(ConvertedGT.shape[0])

for i in range(len(Samples.shape[0])):
    if i != Samples.shape[0]-1:
        Row = np.random.choice(ConvertedGTRows[(Indices[i]+int(NumSegments/4)):(Indices[i+1]-int(NumSegments/4))], 1, p=np.repeat(1/int(NumSegments/2+1), int(NumSegments/2)+1))
        ConvertedSamples[i] = ConvertedGT[Row][:]
        Samples[i] = GT[Row][:][:]
        RefSegment[i] = Ref[Row][0]
        VarSegment[i] = Var[Row]
    else:
        Row = np.random.choice(ConvertedGTRows[(Indices[i]+int(Remainder/4)):(ConvertedGT.shape[0]-int(Remainder/4))], 1, p=np.repeat(1/(Remainder/2+1), int(Remainder/2+1)))
        ConvertedSamples[i] = ConvertedGT[Row][:]
        Samples[i] = GT[Row][:][:]
        RefSegment[i] = Ref[Row][0]
        VarSegment[i] = Var[Row]


print(RefSegment)
print(Samples)
print(ConvertedSamples) 
print(VarSegment)

In [ ]:
### There is bug
RawSequenceSegment1 = np.array([np.repeat('A', RefSegment.shape[0])])
RawSequenceSegment2 = np.array([np.repeat('A', RefSegment.shape[0])])
RawSequenceSegment = np.array([RawSequenceSegment1, RawSequenceSegment2]).T
RawSequenceSegmentTest = np.array([RawSequence1, RawSequence2]).T
for i in range(Samples.shape[1]-1):
    RawSequenceSegment = np.append(RawSequenceSegment, RawSequenceSegmentTest, axis = 1)
print(RawSequenceSegment.shape)

for i in range(Samples.shape[1]):
    Sequence = WriteSequence(RefSegment, VarSegment, Samples[:, i, :])
    RawSequenceSegment[:, i, :] = Sequence

In [ ]:
### Mean center the ConvertedSamples
mean = np.mean(ConvertedSamples, axis = 1)
stdev = np.std(ConvertedSamples, axis = 1)

meanMatrix = np.array([mean for i in range(ConvertedSamples.shape[1])])
stdevMatrix = np.array([stdev for i in range(ConvertedSamples.shape[1])])
ConvertedSamplesStandardized = (ConvertedSamples - meanMatrix)/stdevMatrix

In [ ]:
pca = PCA(n_components=2)
PCs = pca.fit_transform(ConvertedSamples)

In [ ]:
ConvertedSamplesProj1 = ConvertedSamples.T@PCs[:, 0]
ConvertedSamplesProj2 = ConvertedSamples.T@PCs[:, 1]

plt.scatter(SamplesProj1, SamplesProj2)